export const STATES_LIST = [
    { id: 1, stateName: 'Andhra Pradesh', capital: 'Amaravati' },
    { id: 2, stateName: 'Arunachal Pradesh', capital: 'Itanagar' },
    { id: 3, stateName: 'Assam', capital: 'Dispur' },
    { id: 4, stateName: 'Bihar', capital: 'Patna' },
    { id: 5, stateName: 'Chhattisgarh', capital: 'Raipur' },
    { id: 6, stateName: 'Goa', capital: 'Panaji' },
    { id: 7, stateName: 'Gujarat', capital: 'Gandhinagar' },
    { id: 8, stateName: 'Haryana', capital: 'Chandigarh' },
    { id: 9, stateName: 'Himachal Pradesh', capital: 'Shimla' },
    { id: 10, stateName: 'Jharkhand', capital: 'Ranchi' },
    { id: 11, stateName: 'Karnataka', capital: 'Bengaluru' },
    { id: 12, stateName: 'Kerala', capital: 'Thiruvananthapuram' },
    { id: 13, stateName: 'Madhya Pradesh', capital: 'Bhopal' },
    { id: 14, stateName: 'Maharashtra', capital: 'Mumbai' },
    { id: 15, stateName: 'Manipur', capital: 'Imphal' },
    { id: 16, stateName: 'Meghalaya', capital: 'Shillong' },
    { id: 17, stateName: 'Mizoram', capital: 'Aizawl' },
    { id: 18, stateName: 'Nagaland', capital: 'Kohima' },
    { id: 19, stateName: 'Odisha', capital: 'Bhubaneswar' },
    { id: 20, stateName: 'Punjab', capital: 'Chandigarh' },
    { id: 21, stateName: 'Rajasthan', capital: 'Jaipur' },
    { id: 22, stateName: 'Sikkim', capital: 'Gangtok' },
    { id: 23, stateName: 'Tamil Nadu', capital: 'Chennai' },
    { id: 24, stateName: 'Telangana', capital: 'Hyderabad' },
    { id: 25, stateName: 'Tripura', capital: 'Agartala' },
    { id: 26, stateName: 'Uttar Pradesh', capital: 'Lucknow' },
    { id: 27, stateName: 'Uttarakhand', capital: 'Dehradun' },
    { id: 28, stateName: 'West Bengal', capital: 'Kolkata' },
];

export const IMG_URL = "https://media.istockphoto.com/id/931097020/photo/india-flag-waving-background.webp?b=1&s=170667a&w=0&k=20&c=6bbDcoPNXghH9vpXEoHS9CA13fvsByfO9PfnR9y9nAc=";